### ISSUE TITLE
fir-cli version：2.0.9  上传后ios icon图标被替换了

### ISSUE THREAD

**Issue by Derkin** [PGYER/fir-cli#283]

**Comment by Derkin** [comment]
fir-cli version：2.0.9  上传后ios icon图标被替换了

**Comment by jicheng1014** [comment]
https://github.com/FIRHQ/fir-cli/issues/279

参见这里

**Comment by Immmmmmortal1** [comment]
我的fil_cli 使用gem install fir-cli 安装显示安装的最新版,但是通过 bundle exec fastlane update_plugins 更新 显示 0.1.1.版本什么原因?

**Comment by jicheng1014** [comment]
是因为我没更新  我去更新下

**Comment by jicheng1014** [comment]
2.0.19 似乎修复了这个问题, 建议升级到最新版本试试
