### ISSUE TITLE
飞书通知的name没取到

### ISSUE THREAD

**Issue by lionnner** [PGYER/fir-cli#321]
![fir.upload](https://user-images.githubusercontent.com/19425203/125270931-c229e300-e33c-11eb-9a8d-f0b6842b53fd.png)

![feishu_notifier](https://user-images.githubusercontent.com/19425203/125271060-e980b000-e33c-11eb-88fe-215c5d2e11b0.png)

[18:06:01]: ▸ I, [2021-07-12T18:05:52.008545 #87491]  INFO -- : fir-cli version 2.0.14 (2.6.3 @ x86_64-darwin19)

**Comment by jicheng1014** [comment]
额  下个版本解决

**Comment by jicheng1014** [comment]
已经有了
