### ISSUE TITLE
iOS 通过命令上传ipa发生错误麻烦帮排查下谢谢

### ISSUE THREAD

**Issue by oldBlackComing** [PGYER/fir-cli#329]
I, [2022-04-27T18:12:48.625432 #94678]  INFO -- : ✈ -------------------------------------------- ✈
I, [2022-04-27T18:12:48.625459 #94678]  INFO -- : begin to upload ...
I, [2022-04-27T18:12:48.625481 #94678]  INFO -- : fir-cli version 2.0.14 (2.6.8 @ universal.x86_64-darwin21)
D, [2022-04-27T18:12:48.625564 #94678] DEBUG -- : begin to upload icon
D, [2022-04-27T18:12:48.625939 #94678] DEBUG -- : icon_url = https://fir-app-icon.oss-cn-beijing.aliyuncs.com/3147408d758f084bb76d53276c6fff5b2716a518, icon_info = #<File:0x00007fd4c9a01810>
D, [2022-04-27T18:12:48.729721 #94678] DEBUG -- : begin to callback api
D, [2022-04-27T18:12:48.883364 #94678] DEBUG -- : callback api finished
D, [2022-04-27T18:12:48.883449 #94678] DEBUG -- : upload icon finished
D, [2022-04-27T18:12:48.883481 #94678] DEBUG -- : begin to upload binary ...
D, [2022-04-27T18:12:48.883692 #94678] DEBUG -- : binary_url = https://fir-app-binary.oss-cn-beijing.aliyuncs.com/70f76883fb90980eea210b95362eef7382188f1a, binary_info = #<File:0x00007fd4c9b03e98>
D, [2022-04-27T18:12:48.883752 #94678] DEBUG -- : {"CONTENT-DISPOSITION"=>"attachment; filename* = UTF-8''EEOClient-v%24MARKETING_VERSION.ipa", "Content-Type"=>"application/octet-stream", "date"=>"Wed, 27 Apr 2022 10:12:48 GMT", "x-oss-date"=>"Wed, 27 Apr 2022 10:12:48 GMT", "authorization"=>"OSS LTAIH45wjMAbqQjW:04ra8bgnPYdPf9HHTxw+xLYEK8k="}
E, [2022-04-27T21:13:53.253007 #94678] ERROR -- : upload binary ... error ! 403 Forbidden
E, [2022-04-27T21:13:53.253539 #94678] ERROR -- : binary upload to ali fail, 403 Forbidden

**Comment by jicheng1014** [comment]
没权限上传呀
