### ISSUE TITLE
c::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. 

### ISSUE THREAD

**Issue by kennenfromchina** [PGYER/fir-cli#330]
When I finished installing via `gem install fir-cli` , the following warning appeared when I checked the version number
```shell
fir -v

Calling `c::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
✈ fir-cli 2.0.14
```

**Comment by luoluoluolin** [comment]
我也遇到这个问题

**Comment by jicheng1014** [comment]
哦？  想请问下  这边按照是  通过 rvm 还是  系统 ruby 直接安装的呀

**Comment by kennenfromchina** [comment]
> 哦？ 想请问下 这边按照是 通过 rvm 还是 系统 ruby 直接安装的呀

rvm

**Comment by jicheng1014** [comment]
我试了下 好像没报   麻烦您这边  说下您的操作系统   rvm  版本  以及  安装的ruby 版本   我这看下是否能复现    谢谢了

**Comment by kennenfromchina** [comment]
> 我试了下 好像没报 麻烦您这边 说下您的操作系统 rvm 版本 以及 安装的ruby 版本 我这看下是否能复现 谢谢了

不好意思，之前重装系统了，现在用的是系统ruby
 ~  ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
 ~  fir -v
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
✈ fir-cli 2.0.15
 ~  gem -v
3.3.11

**Comment by xiehui999** [comment]
+1

**Comment by jicheng1014** [comment]
最新版本已经解决了这个问题了
