### ISSUE TITLE
依赖的 thor 版本太老了

### ISSUE THREAD

**Issue by Abson** [PGYER/fir-cli#334]
Bundler could not find compatible versions for gem "thor":
  In Gemfile:
    fastlane-plugin-fir_cli (~> 2.0, >= 2.0.15.1) was resolved to 2.0.15.1, which depends on
      fir-cli (~> 2.0.15) was resolved to 2.0.15, which depends on
        thor (~> 0.19)

目前使用的 thor 依赖太老了，导致使用的其他插件版本冲突，如果可以的话，更新一下吧

**Comment by jicheng1014** [comment]
老哥   有个  go 版本的, 可以试用一下

https://github.com/PGYER/go-fir-cli/releases

**Comment by Abson** [comment]
@jicheng1014 兄弟，我们用的是 fastlane，用的 ruby，不想再装个 go

**Comment by jicheng1014** [comment]
已更新
