### ISSUE TITLE
fir-cli publish 失败

### ISSUE THREAD

**Issue by RickwangF** [PGYER/fir-cli#336]
/var/folders/h9/h3cjgnpx0xb_2b6d7k7tcs4h0000gn/T/3a884b1ccab757e93b4e77c768c8aa378680ec27_git_mall_ios
undefined method `body' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.1/lib/api_tools/default_rest_module.rb:75:in `basic_request'
/Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.1/lib/api_tools/default_rest_module.rb:10:in `block (2 levels) in <module:DefaultRestModule>'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util.rb:36:in `fetch_user_info'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/publish.rb:216:in `initialize_publish_options'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/publish.rb:15:in `publish'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/cli.rb:147:in `publish'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/cli.rb:194:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by RickwangF** [comment]
项目编译成功，ipa导出成功，但是fir push 的时候就报错，没有其他报错信息

**Comment by jicheng1014** [comment]
老哥, 升级下gem. 即执行 gem install fir-cli 升级到最新版本 即可
