### ISSUE TITLE
fir-cli 2.0.18 上传的包下载不了，点击下载后网页提示不能安装

### ISSUE THREAD

**Issue by xiaocode337317439** [PGYER/fir-cli#338]
上传命令 fir p xxxx.apk -c 'xxxx' -Q -T tokenxxxx

**Comment by jicheng1014** [comment]
老哥 我这边用 2.0.18 是可以的, 同时没有接到其他用户关于 2.0.18 版本的app 下载不了的问题, 建议您检查下apk 文件, 在 本地确认是否可以安装
