### ISSUE TITLE
上传报错

### ISSUE THREAD

**Issue by Zzh95** [PGYER/fir-cli#339]
progress: 99.06%
progress: 99.69%
upload finished
D, [2023-04-23T11:21:23.955367 #9488] DEBUG -- : begin to callback api
E, [2023-04-23T11:21:23.955568 #9488] ERROR -- : upload binary ... error ! "\x9E" followed by "," on GBK
E, [2023-04-23T11:21:23.955689 #9488] ERROR -- : binary upload to ali fail, "\x9E" followed by "," on GBK

上传快成功了，一直返回这个错误导致失败
ruby版本和fir版本分别是
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x64-mingw32]
fir-cli 2.0.21

**Comment by jicheng1014** [comment]
老哥您可能遇到的是windows 的编码问题, 

建议您将编码从 GBK 改为 utf8 

或者使用 powershell 启动shell

**Comment by Zzh95** [comment]
确实是这个问题，刚刚把cmd的编码格式改了之后就上传成功了，谢谢了
