### ISSUE TITLE
M1设备的mac怎么集成

### ISSUE THREAD

**Issue by youyoukong** [PGYER/fir-cli#340]
M1设备的mac怎么集成, 已经用rosetta打开终端了.gem install fir-cli后显示成功, 但是跟着fir -v就报错zsh: command not found: fir.

**Comment by youyoukong** [comment]
自己解决了sudo gem install -n /usr/local/bin fir-cli

**Comment by jicheng1014** [comment]
我自己的机器是 m2pro 跑的很欢乐呀

**Comment by jicheng1014** [comment]
感觉您这个应该像是环境变量惹的祸

**Comment by youyoukong** [comment]
> 感觉您这个应该像是环境变量惹的祸

可能是吧, 现在用的路径是x86的路径.能跑了.
