### ISSUE TITLE
fir 上传错误   invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by dust365** [PGYER/fir-cli#341]
## 上传指定路径后，报如下的错误，卸载ruby 重装后依然如此？请问下是什么问题？卡了好几天了

invalid byte sequence in UTF-8
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor/parser/options.rb:168:in `==='
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor/parser/options.rb:168:in `current_is_switch?'
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor/parser/options.rb:95:in `parse'
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor/base.rb:79:in `initialize'
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor/invocation.rb:26:in `initialize'
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor/shell.rb:45:in `initialize'
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor.rb:388:in `new'
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor.rb:388:in `dispatch'
/Users/client/.rvm/gems/ruby-2.6.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/Users/client/.rvm/gems/ruby-2.6.0/gems/fir-cli-2.0.21/bin/fir:8:in `<top (required)>'

**Comment by jicheng1014** [comment]
感觉像是编码问题？   https://github.com/PGYER/fir-cli/issues/339
