### ISSUE TITLE
fir上传ipa报错 

### ISSUE THREAD

**Issue by smile678** [PGYER/fir-cli#342]
E, [2023-08-08T17:31:00.603574 #42084] ERROR -- : upload binary ... error ! SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
E, [2023-08-08T17:31:00.603734 #42084] ERROR -- : binary upload to ali fail, SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

**Comment by jicheng1014** [comment]
老哥 升级下您的 fir-cli 版本?
